
-- Create the hackathons table
CREATE TABLE IF NOT EXISTS public.hackathons (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    organizer text,
    date text,
    mode text,
    tags text[],
    color text
);

-- Enable Row Level Security
ALTER TABLE public.hackathons ENABLE ROW LEVEL SECURITY;

-- Allow anyone to read hackathons
CREATE POLICY "Anyone can read hackathons"
ON public.hackathons
FOR SELECT
TO anon, authenticated
USING (true);
